[package]
name = "nxrm_two_portal"
version = "0.1.0"
edition = "2021"
description = "Translate the subset of the NXRM2 API into the new Central Portal Publisher API"

[dependencies]
axum = { version = "0.7.4", features = ["tracing", "macros"] }
color-eyre = "0.6.2"
eyre = "0.6.12"
tokio = { version = "1.36.0", features = ["macros", "fs", "rt-multi-thread", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

