[package]
name = "portal_api"
version = "0.1.0"
edition = "2021"
description = "API Client for the Maven Central Publisher Portal"

[dependencies]
eyre = "0.6.11"
reqwest = { version = "0.11.23", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.193", features = ["derive"] }
